#!/usr/bin/env python
from ctypes import c_void_p, c_uint, c_char_p, c_uint64, cdll
import asyncio
from cuemsutils.ComunicatorServices import Comunicator
import systemd.daemon



try:
    libmtcmaster = cdll.LoadLibrary('libmtcmaster.so.0')
except:
    libmtcmaster = None
    raise ImportError('libmtcmaster import error')

# void* MTCSender_create()
libmtcmaster.MTCSender_create.argtypes = None
libmtcmaster.MTCSender_create.restype = c_void_p

# void MTCSender_release(void* mtcsender);
libmtcmaster.MTCSender_release.argtypes = [c_void_p]
libmtcmaster.MTCSender_release.restype = None

# void MTCSender_openPort(void* mtcsender, unsigned int portnumber, const char* portname);
try:
    libmtcmaster.MTCSender_openPort.argtypes = [c_void_p, c_uint, c_char_p]
    libmtcmaster.MTCSender_openPort.restype = None
except:
    libmtcmaster.MTCSender_openPort = None

# void MTCSender_play(void* mtcsender);
libmtcmaster.MTCSender_play.argtypes = [c_void_p]
libmtcmaster.MTCSender_play.restype = None

# void MTCSender_stop(void* mtcsender);
libmtcmaster.MTCSender_stop.argtypes = [c_void_p]
libmtcmaster.MTCSender_stop.restype = None

# void MTCSender_pause(void* mtcsender);
libmtcmaster.MTCSender_pause.argtypes = [c_void_p]
libmtcmaster.MTCSender_pause.restype = None

# void MTCSender_setTime(void* mtcsender, uint64_t nanos);
libmtcmaster.MTCSender_setTime.argtypes = [c_void_p, c_uint64]
libmtcmaster.MTCSender_setTime.restype = None



class MtcmasterRunner():


    def __init__(self):
        self.mtcmaster = libmtcmaster.MTCSender_create()
        self.address = "ipc:///tmp/cuems/libmtcmaster.sock"
        self.comunicator = Comunicator(address = self.address)
        self.command = {'play': self.play, 'pause': self.pause,'stop': self.stop,'set_time': self.set_time}

    def process_request(self, request):
        try:
            if 'params' in request:  # Check if the request is valid
                self.command.get(request['cmd'])(request['params']['nanos']) 
            else:
                self.command.get(request['cmd'])()
            return {'resp': 'ok'}
        except Exception as e:
            print(f"Error while processing request: {e}")
            return {'resp': f"Error while processing request: {e}"}

    async def run(self):
        # The "server" thread has its own asyncio loop
        systemd.daemon.notify('READY=1')
        await self.comunicator.reply(self.process_request)

    def stop_server(self):
        self.stop()  # Stop the MTC master playback
        self.release()
        asyncio.get_event_loop().stop()  # Stop the server's event loop


    def play(self):
        libmtcmaster.MTCSender_play(self.mtcmaster)
        print("MTC master started playing.")


    def stop(self):
        libmtcmaster.MTCSender_stop(self.mtcmaster)

    def pause(self):
        libmtcmaster.MTCSender_pause(self.mtcmaster)
    
    def set_time(self, nanos):
        libmtcmaster.MTCSender_setTime(self.mtcmaster, nanos)
    
    def release(self):
        libmtcmaster.MTCSender_release(self.mtcmaster)
    
    def __del__(self):
        self.release()




if __name__ == "__main__":
    asyncio.run(MtcmasterRunner().run())

